# Generated by Django 4.2 on 2023-06-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menuhandler", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuhandler",
            name="web_url",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
