# Generated by Django 4.2 on 2023-06-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menuhandler", "0002_alter_menuhandler_web_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuhandler",
            name="has_sub_menu",
            field=models.IntegerField(default=0),
        ),
    ]
