# Generated by Django 4.2 on 2023-06-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesspartner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspartner',
            name='short_image_description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
