# Generated by Django 4.2 on 2023-06-03 11:01

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='boardmember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=50)),
                ('member_designation', models.CharField(max_length=100)),
                ('member_profile', tinymce.models.HTMLField()),
            ],
        ),
    ]
