# Generated by Django 4.2 on 2023-06-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="loanproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("loan_title", models.CharField(max_length=50)),
                ("loan_amount", models.CharField(max_length=150)),
                ("loan_roi", models.CharField(max_length=150)),
                ("loan_tenure", models.CharField(max_length=150)),
            ],
        ),
    ]
