# Generated by Django 4.2 on 2023-06-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanproduct", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loanproduct",
            name="loan_image",
            field=models.FileField(
                default=None, max_length=250, null=True, upload_to="loan-product/"
            ),
        ),
    ]
