# Generated by Django 4.2 on 2023-06-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=150)),
                ('slider_short_description', models.CharField(max_length=150)),
                ('slider_images', models.FileField(default=None, max_length=250, null=True, upload_to='slider/')),
            ],
        ),
    ]
