# Generated by Django 4.2 on 2023-06-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menuhandler', '0001_initial'),
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='menuhandler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menuhandler.menuhandler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='slider_url',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_images',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='slider/%y%m%d'),
        ),
    ]
