# Generated by Django 4.2 on 2023-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slider", "0002_slider_menuhandler_slider_slider_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="slider_short_description",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="slider_title",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
