# Generated by Django 4.2 on 2023-06-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slider", "0003_alter_slider_slider_short_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="slider_short_description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="slider",
            name="slider_title",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
