# Generated by Django 4.2 on 2023-06-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("slider", "0004_alter_slider_slider_short_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slider",
            name="slider_title",
            field=models.CharField(max_length=150),
        ),
    ]
