# Generated by Django 4.2 on 2023-06-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_setting_facebook_url_setting_linkedin_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='website_logo',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='logo/'),
        ),
    ]
