# Generated by Django 4.2 on 2023-06-07 19:20

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("setting", "0004_setting_website_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="registered_address",
            field=tinymce.models.HTMLField(),
        ),
    ]
