# Generated by Django 4.2 on 2023-06-05 13:56

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("businessprocess", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="businessprocessdescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("description", tinymce.models.HTMLField()),
                (
                    "businessprocess",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="businessprocess.businessprocess",
                    ),
                ),
            ],
        ),
    ]
