# Generated by Django 4.2 on 2023-06-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businessprocessdescription", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprocessdescription",
            name="color",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
