# Generated by Django 4.2 on 2023-06-03 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menuhandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='submenuhandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(max_length=100, null=True)),
                ('subweb_url', models.CharField(max_length=100, null=True)),
                ('menuhandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menuhandler.menuhandler')),
            ],
        ),
    ]
